### ISSUE TITLE
Hello, can you provide me with relevant resources about ben nanonote?

### ISSUE THREAD

**Issue by a381427345** [pyneo/pyneo.github.io#1]
I have a Ben NanoNote, but its NAND size is 1GB. When I was looking for information, I found that your server had relevant resources a long time ago. I don't know if it is still available now. Thank you for your help.

**Comment by emdete** [comment]
i abandomed all work on that device. cause is that the hw is of miserable quality meaning for example that the nand is unstable and content changes at will. it was no fun to develop for it.

but if you want to give it a try let me know how / where i can drop you the files i have.

**Comment by a381427345** [comment]
Thank you very much for your reply.
I've even given up.
I saw your file on the Wayback machine. There are 1gb nand nanonote related files on it, but it can no longer be downloaded. Can you provide me with this part of the document?

If possible, can we use communication software or email to communicate?

**Comment by emdete** [comment]
yes, we can, no clue  if github provides a private way to exchange adresses. i prefere email or matrix.

**Comment by a381427345** [comment]
![S41018-08260407_im vector app](https://github.com/user-attachments/assets/cb5ab8d0-4f6f-49fb-bce3-3ce78e18edb4)

this？
E-mail:381427345@qq.com

**Comment by a381427345** [comment]
> 是的，我们可以，不知道 GitHub 是否提供了一种私人的方式来交换地址。我更喜欢电子邮件或矩阵。

hello,Did you encounter any problems?
I haven’t received a reply to my email or matrix.
Is there something I didn't do correctly?
